config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  resources :users
  resources :groups do
    resources :transactions
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true

  def sum_total
    transactions.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :transactions, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    groups_path
  end
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    if @group.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to groups_path
    else
      flash[:error] = 'Error creating Group'
      redirect_to new_groups_path(@group)
    end
  end

  def destroy
    if @group.destroy
      flash[:notice] = 'Category was successfully destroyed.'
      redirect_to @group
    else
      flash[:error] = 'Error deleting category'
    end
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_group, only: %i[new create edit update destroy]
  before_action :set_transaction, only: %i[edit update destroy]

  def index
    @group = Group.where(user_id: current_user.id, id: params[:group_id])
  end

  def new
    @transaction = Transaction.new
    @group = Group.where(user_id: current_user)
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.group_id = @group.id

    if @transaction.save
      flash[:notice] = 'Transaction was successfully created.'
      redirect_to group_transactions_path
    else
      flash[:error] = 'Error creating transaction'
      redirect_to new_group_transaction_path(@group)
    end
  end

  def destroy
    if @transaction.destroy
      flash[:notice] = 'Transaction was successfully created.'
      redirect_to group_path
    else
      flash[:error] = 'Error creating transaction'
    end
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  # before_action :authenticate_user!
  def index
    @users = current_user # current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class='container' >
    <div class='loginForm'>

        <h4 class='list-of-category'>Lists of Category</h4>

        <%if (@groups.any?)%>
        <div >
         <ul class='category-list'>
            <% @groups.each do |group| %>
            
                <li>
                    <%= link_to group_transactions_path(group.id) do %>
                    <%= render partial: "shared/group", locals: { group: group } %>
                    <% end %>
                </li>
            
            <% end %>
            </ul>
        </div>
        <% else %>
            <h3>'Category records not found!'</h3>
        <% end %>
        <br>
        <%= link_to "Add Category", new_group_path, class:'add-category'%>
    </div>
</div>

app/views/groups/new.html.erb
<div class='container' >
  <div class='loginForm-add-new-category'>

        <h2>Add New Category</h2>
        <br>
        <%= render partial: "shared/new_group_form", group: @group %>
        <br>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/menu', locals: {user: current_user} %>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_group.html.erb
<div class='category-item-transaction'>
    <div class='category-name-icon'>
        <div><b><%= group.name %></b></div>
        <div><%= group.icon  %></div>
    </div>
    <div class='category-transaction'>
       <div> Total Amounts: </div>
       <div>$<%= group.sum_total %> </div>
    </div>
</div>

app/views/shared/_menu.html.erb
  <ul class="header-menu">
  <% if user_signed_in? %>
      <li class= 'nav-link'>
        <% if user_signed_in? %>
          <%= link_to groups_path do %>
            <span class="material-symbols-outlined back">arrow_back_ios</span>
          <% end %>
        <% else %>
          <%= link_to root_path do %>
            <span class="material-symbols-outlined back">arrow_back_ios</span>
          <% end %>
        <% end %>
      </li>
      <li ><%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link' %></li>
  <% end %>
  </ul>

app/views/shared/_new_group_form.html.erb
<div class='container' >
  <div class='loginForm-add-new-category'>
        <%= form_with(model: @group) do |f| %>

            <div><%= f.text_field :name, value: @group.name, placeholder: "Enter Category Name", required: true%> </div><br>

            <div >
                <%= f.label :icon, 'Select Icon:', class: "select_icon_label" %>
                <%= f.select :icon, ["👔","🎵","🎉","🎁","🍼","🏠", "🐶", "🍻", "🍔"], value: @group.icon, required: true%>
            </div>
            <br>
            <%= f.submit "Save Category", class: 'add-button'%>
        <% end %> 
    </div>
</div>

app/views/transactions/index.html.erb
<div class='container' >
  <div class='loginForm-transaction-list'>

    <h2>Transactions Lists</h2>

    <% @group.each do |group| %>
      <div class='transaction-container'>
        <%= render partial: "shared/group", locals: { group: group } %>
      </div>
      <br>
      <div class='transaction-container'>
        <div class='title-transaction'>
          <span>Items</span>
          <span class='item-amount'>Amount</span>
        </div>
        <% group.transactions.order("created_at DESC").each do |t| %>
            <div class="item-transaction">
              <div><%= t.name %></div>
              <div class='item-amount'>$<%= t.amount %></div>
            </div>
          <% end %>
        </div>
        <br>
        <%= button_to link_to "New Transaction", new_group_transaction_path(group) %>

    <% end %>
  </div>
</div>

app/views/transactions/new.html.erb
<div class='container' >
  <div class='loginForm-new-transaction'>

      <h2>New Transactions</h2>
       <br>
      <%= form_with model: @transaction, url: group_transactions_path  do |f|%>

        <div class="form_inputs">
          <div>
            <%= f.text_field :name, required: true, placeholder: "Name of New Transaction"%>
          </div>
          <br>
          <div>
            <%= f.number_field :amount, required: true, placeholder: "Price of Items"%>
          </div>

        </div>
        <br>
        <%= f.submit "Add New Transaction", class: "add-button"%>
        <% end %>
        <br>
        <%= link_to "Cancel", group_transactions_path %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container' >
  <div class='loginForm-home'>
    <h4>Budget App by Amrendra K</h4>
    <img class="splash-image" src="<%= image_path("budget_logo.png") %>" alt="splash_icon"/> <br>
    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
    <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
  </div>
</div>